/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package passwordmanagergui;

import passwordmanager.manager.Logger;
import passwordmanager.manager.Manager;
import passwordmanagergui.group.MainWindow;

public class App {
    public static void main(String[] args) {
        initializePasswordManager();
        launchApp();
    }

    public static void initializePasswordManager() {
        boolean needsLogs = false;
        boolean needRawDataChecked = true;
        boolean needMapStorage = false;
        boolean needThreadEncoder = true;
        Manager.initialize(needsLogs, needRawDataChecked, needMapStorage, needThreadEncoder);
    }

    public static void launchApp() {
        MainWindow mainWindow = new MainWindow();
        mainWindow.create();

        for (String log : Logger.getLogs()) {
            System.out.println(log);
        }
    }
}
